add_newline = false

format = "\\[$username@$hostname:$directory:\\($git_branch$git_status\\)\\]$character"

[username]
show_always = true
format = "[$user](bold green)"

[hostname]
ssh_only = false
format = "[$hostname](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path](bold blue)"

[git_branch]
symbol = "🌿 "
format = "[$branch](bold mauve)"

[git_status]
format = " [($staged$modified$untracked$ahead_behind)]($style)"
style = "bold"

staged = "[+](green)"
modified = "[*](yellow)"
untracked = "[?](red)"

ahead = "[⇡${count}](cyan)"
behind = "[⇣${count}](cyan)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](cyan)"
up_to_date = ""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold green)"
